import json
from dataclasses import dataclass
from typing import Iterable

from core.process import run_executable


POWERSHELL = "powershell.exe"

# These are only recommendation hints. Removal is always exact-package based
# and the UI never performs wildcard deletion.
RECOMMENDED_NAMES = (
    "3DViewer",
    "BingNews",
    "BingWeather",
    "Clipchamp",
    "DevHome",
    "FeedbackHub",
    "GetHelp",
    "Getstarted",
    "Microsoft.MicrosoftSolitaireCollection",
    "MicrosoftTeams",
    "MSTeams",
    "PowerAutomate",
    "People",
    "Xbox",
)

PROTECTED_NAMES = {
    "Microsoft.WindowsStore",
    "Microsoft.DesktopAppInstaller",
    "Microsoft.Windows.SecHealthUI",
    "MicrosoftWindows.Client.CBS",
    "Microsoft.Windows.StartMenuExperienceHost",
}


@dataclass(frozen=True)
class AppxPackage:
    name: str
    package_full_name: str
    version: str
    publisher: str
    install_location: str
    is_framework: bool
    non_removable: bool
    signature_kind: str
    status: str
    scope: str = "Current user"

    @property
    def removable(self):
        return (
            not self.is_framework
            and not self.non_removable
            and self.name not in PROTECTED_NAMES
        )

    @property
    def recommended(self):
        if not self.removable:
            return False
        lowered = self.name.lower()
        return any(token.lower() in lowered for token in RECOMMENDED_NAMES)


def _powershell(script, timeout=120):
    encoded = script.encode("utf-16le")
    import base64

    command = base64.b64encode(encoded).decode("ascii")
    return run_executable(
        POWERSHELL,
        ("-NoProfile", "-NonInteractive", "-EncodedCommand", command),
        timeout=timeout,
    )


def _as_list(payload):
    if payload is None:
        return []
    if isinstance(payload, list):
        return payload
    return [payload]


def inventory(all_users=False):
    scope = "All users" if all_users else "Current user"
    selector = "-AllUsers" if all_users else ""
    script = f"""
$ErrorActionPreference = 'Stop'
Get-AppxPackage {selector} |
  Select-Object Name, PackageFullName, Version, Publisher, InstallLocation,
    IsFramework, NonRemovable, SignatureKind, Status |
  Sort-Object Name, PackageFullName |
  ConvertTo-Json -Depth 4 -Compress
"""
    result = _powershell(script)
    if result.returncode != 0:
        raise RuntimeError(result.stderr or "Get-AppxPackage failed.")
    if not result.stdout:
        return []
    try:
        rows = _as_list(json.loads(result.stdout))
    except json.JSONDecodeError as exc:
        raise RuntimeError("Windows returned invalid AppX inventory data.") from exc

    return [
        AppxPackage(
            name=str(row.get("Name") or ""),
            package_full_name=str(row.get("PackageFullName") or ""),
            version=str(row.get("Version") or ""),
            publisher=str(row.get("Publisher") or ""),
            install_location=str(row.get("InstallLocation") or ""),
            is_framework=bool(row.get("IsFramework")),
            non_removable=bool(row.get("NonRemovable")),
            signature_kind=str(row.get("SignatureKind") or ""),
            status=str(row.get("Status") or ""),
            scope=scope,
        )
        for row in rows
        if row.get("Name") and row.get("PackageFullName")
    ]


def remove_packages(packages: Iterable[str], all_users=False):
    packages = [str(package) for package in packages if package]
    if not packages:
        return "No AppX packages selected."

    # Exact full names only. The PowerShell command deliberately rejects
    # wildcard input and uses the package list generated by inventory().
    commands = []
    for package in packages:
        escaped = package.replace("'", "''")
        switch = " -AllUsers" if all_users else ""
        commands.append(
            f"Remove-AppxPackage -Package '{escaped}'{switch} -ErrorAction Stop"
        )

    script = "$ErrorActionPreference = 'Stop'; " + "; ".join(commands)
    result = _powershell(script, timeout=300)
    if result.returncode != 0:
        raise RuntimeError(result.stderr or "AppX removal failed.")
    scope = "all users" if all_users else "the current user"
    return f"Removed {len(packages)} AppX package(s) for {scope}."


def register_existing_manifest(install_location):
    if not install_location:
        raise ValueError("The package has no recorded installation location.")
    script = f"""
$ErrorActionPreference = 'Stop'
$location = '{install_location.replace("'", "''")}'
$manifest = Join-Path $location 'AppxManifest.xml'
if (-not (Test-Path -LiteralPath $manifest)) {{
    throw "AppxManifest.xml was not found at $manifest"
}}
Add-AppxPackage -Path $manifest -Register -DisableDevelopmentMode -ErrorAction Stop
"""
    result = _powershell(script, timeout=180)
    if result.returncode != 0:
        raise RuntimeError(result.stderr or "AppX registration failed.")
    return "Existing AppX files were registered for the current user."


def describe(packages):
    return "\n".join(
        f"{package.name} | {package.version} | "
        f"{'Recommended' if package.recommended else 'Review'} | "
        f"{'Removable' if package.removable else 'Protected'}"
        for package in packages
    )
