import importlib


MODULES = (
    "app",
    "main",
    "core.backup",
    "core.configuration",
    "core.configuration_engine",
    "core.executor",
    "core.jobs",
    "core.logging",
    "core.operation_receipts",
    "core.process",
    "core.profile_execution",
    "core.profile_manager",
    "core.recovery",
    "core.registry",
    "core.scheduler",
    "core.system_info",
    "modules.appx",
    "modules.browser_extensions",
    "modules.catalog",
    "modules.developer_center",
    "modules.dns_center",
    "modules.gaming_center",
    "modules.hardware_monitor",
    "modules.maintenance",
    "modules.network_center",
    "modules.power_center",
    "modules.repair",
    "modules.repair_center",
    "modules.service_manager",
    "modules.services",
    "modules.software",
    "modules.startup",
    "modules.startup_manager",
    "modules.storage_center",
    "modules.system_snapshot",
    "modules.windows_features",
    "modules.windows_update",
    "ui.activity",
    "ui.appx",
    "ui.browser_extensions",
    "ui.developer_center",
    "ui.gaming_center",
    "ui.maintenance",
    "ui.profile_manager",
    "ui.software",
    "ui.storage_center",
    "ui.system_dashboard",
    "ui.theme",
    "ui.windows_management",
)


def test_major_modules_import_cleanly():
    for module_name in MODULES:
        importlib.import_module(module_name)
